// <auto-generated />
namespace KursachV4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class test2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test2));
        
        string IMigrationMetadata.Id
        {
            get { return "201701022130474_test2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
