// <auto-generated />
namespace KursachV4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class test3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test3));
        
        string IMigrationMetadata.Id
        {
            get { return "201701022253022_test3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
