//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachV4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Arraiving
    {
        public int Id { get; set; }

        [Display(Name="Прізвище провайдера")]
        public Nullable<int> ProviderId { get; set; }

        [Display(Name="Назва металу")]
        public Nullable<int> ScrapId { get; set; }

        [Display(Name="Дата прибуття")]
        public Nullable<System.DateTime> ArravingDate { get; set; }

        [Display(Name="Вартість за од")]
        public double Cost { get; set; }

        [Display(Name="Кількість")]
        public double Amount { get; set; }

        [Display(Name = "Назва складу")]
        public Nullable<int> StoreId { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Scrap Scrap { get; set; }
        public virtual Store Store { get; set; }
    }
}
