//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachV4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Consumption
    {
        public int Id { get; set; }

        [Display(Name = "Назва компанії")]
        public Nullable<int> ReceiverId { get; set; }

        [Display(Name = "Назва металу")]
        public Nullable<int> ScrapId { get; set; }

        [Display(Name = "Дата отримання")]
        public Nullable<System.DateTime> ArravingDate { get; set; }

        [Display(Name = "Вартість")]
        public double Cost { get; set; }

        [Display(Name = "Кілкьість")]
        public double Amount { get; set; }

        [Display(Name = "Назва складу")]
        public Nullable<int> StoreId { get; set; }


    
        public virtual Receiver Receiver { get; set; }
        public virtual Scrap Scrap { get; set; }
        public virtual Store Store { get; set; }
    }
}
