//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachV4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DetailsOfArraivedMetal
    {
        public int Id { get; set; }

        [Display(Name="Густина")]
        public int Density { get; set; }

        [Display(Name = "Опис")]
        public string Description { get; set; }

        [Display(Name = "Назва металу")]
        public Nullable<int> ScrapId { get; set; }

        [Display(Name = "Ціна")]
        public double Cost { get; set; }
    }
}
