//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachV4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Scrap
    {
        public Scrap()
        {
            this.Consumptions = new HashSet<Consumption>();
            this.Arraivings = new HashSet<Arraiving>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Назва")]
        public string Title { get; set; }

        [Display(Name = "Кількість")]
        public double Amount { get; set; }

        [Display(Name = "Густина")]
        public int Density { get; set; }

        [Display(Name = "Опис")]
        public string Description { get; set; }

        [Display(Name = "Назва складу")]
        public Nullable<int> StoreId { get; set; }


    
        public virtual ICollection<Consumption> Consumptions { get; set; }
        public virtual ICollection<Arraiving> Arraivings { get; set; }
        public virtual Store Store { get; set; }
    }
}
