//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachV4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScrapMetal : DbContext
    {
        public ScrapMetal()
            : base("name=ScrapMetal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Consumption> Consumptions { get; set; }
        public DbSet<Provider> Providers { get; set; }
        public DbSet<Receiver> Receivers { get; set; }
        public DbSet<Scrap> Scraps { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<Arraiving> Arraivings { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ColumnsCount> ColumnsCounts { get; set; }
        public DbSet<DetailsOfArraivedMetal> DetailsOfArraivedMetals { get; set; }
        public DbSet<ProviderReceiverInterconnection> ProviderReceiverInterconnections { get; set; }
        public DbSet<VIPProvider> VIPProviders { get; set; }
    }
}
