//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursachV4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Store
    {
        public Store()
        {
            this.Consumptions = new HashSet<Consumption>();
            this.Scraps = new HashSet<Scrap>();
            this.Arraivings = new HashSet<Arraiving>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Назва складу")]
        public string Name { get; set; }

         [Display(Name = "Відповідальний")]
        public string Responsible { get; set; }


    
        public virtual ICollection<Consumption> Consumptions { get; set; }
        public virtual ICollection<Scrap> Scraps { get; set; }
        public virtual ICollection<Arraiving> Arraivings { get; set; }
    }
}
